FROM python:3.9
RUN apt update
RUN apt install net-tools
COPY /api/requirements.txt /app/requirements.txt
RUN pip install --upgrade pip
RUN pip install -r /app/requirements.txt
COPY /python /app/python
COPY /files /app/files
COPY /newman /app/newman
WORKDIR /app/python
CMD ["python" "test_ddr_api"]