mode: url_external
email:
  from: ddr.fgpservices-servicespgf.rdd@aws.nrcan-rncan.cloud
  to: [bergeronpilon@gmail.com]
  host: email-smtp.ca-central-1.amazonaws.com
  user: AKIARHK2ZDWAX5LTKCJH
  password: BCpDDYnkVsrj8gvCTu7LliMq8+ie4C/JB6QZAEByLuVK
  port: 587
  timeout: 10
  tls: True
log: log_path::API_test.log
collections:
#  PyGeoAPI:
#    request: newman run newman_path::PyGeoAPI.json -k -r html,json-summary
#    var_url: urlPyGeoApi
#    url_internal: http://10.68.130.138:5000/openapi
#  CZS_Admin:
#    request: newman run newman_path::CZS_Admin.json -g newman_path::globals.json -k -r html,json-summary
#    var_url: environment
#    url_internal: http://10.68.130.138:5001
#  DDR_Registry:
#    request: newman run newman_path::DDR_Registry.json -g newman_path::globals.json -k -r html,json-summary
#    var_url: environment
#    url_internal:  http://10.68.130.138:5021
  DDR_Puplisher:
    request: newman run newman_path::DDR_Publisher.json -g newman_path::globals.json --env-var "publish_file_zip=newman_path::ddr_publish.zip" -k -r html,json-summary
    var_url: environment
    url_internal:  http://10.68.130.138:5031
