email:
  from: bergeronpilon@gmail.com
  to: bergeronpilon@gmail.com
  subject: "Résultat"
  server: dddd
  port: 445

collections:
  PyGeoAPI:
    requete: newman run PyGeoAPI.json -k
    var_coll: urlPyGeoApi
    internal: http://10.68.130.138:5000/openapi
    external: https://czs-pygeoapi.ddr-stage.services.geo.ca

logger:
  file: log_collection.log