mode: url_internal
var_url: environment
to: [bergeronpilon@gmail.com]
log: log_path::API_test.log
collections:
  clip_zip_ship_api:
    request: newman run newman_path::clip_zip_ship_api.json -k -r html,json-summary
    url_internal: http://10.68.130.138:5000
  clip_zip_ship_registry:
    request: newman run newman_path::clip_zip_ship_registry.json -k -r html,json-summary
    url_internal: http://10.68.130.138:5001
  ddr_registry:
    request: newman run newman_path::ddr_registry.json -k -r html,json-summary
    url_internal:  http://10.68.130.138:5021
  ddr_publication:
    request: newman run newman_path::ddr_publication.json -k -r html,json-summary --env-var "publish_file_zip=newman_path::ddr_publisher.zip"
    url_internal:  http://10.68.130.138:5031
